Repository lunit-io/insight-viewer, pull requests merged in 2022-11, with the labels that each got.

#358 chore(docs): add metadata to set cache header
  .github/workflows/insight-viewer-production.yml
Labels: enhancement

#359 VIEWER-69 / add reset annotation
  apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts
  apps/insight-viewer-docs-e2e/src/support/utils.ts
  apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx
  libs/fixtures/src/annotation/polygons.ts
  libs/insight-viewer/src/hooks/useAnnotation/index.ts
Labels: enhancement

#361 ADD RFC Template
  rfcs/0000_RFC_TEMPLATE.md
Labels: documentation

#362 hotfix / apply Cornerstone resize to useImageDisplay
  libs/insight-viewer/src/hooks/useImageDisplay/index.ts
Labels: bug, patch

#366 VIEWER-90 / feat(docs): add shortkeys in drawing page
  apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx
  apps/insight-viewer-docs/containers/Measurement/Drawer/index.tsx
Labels: enhancement

#367 VIEWER-91 / Fix/select disappear
  libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts
  libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.types.ts
  libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx
  libs/insight-viewer/src/components/EditPointer/index.tsx
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
Labels: bug

#368 Release/6.2.0
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts
  apps/insight-viewer-docs-e2e/src/support/utils.ts
  apps/insight-viewer-docs/CHANGELOG.md
  apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx
  apps/insight-viewer-docs/containers/Measurement/Drawer/index.tsx
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/fixtures/src/annotation/polygons.ts
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts
  libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.types.ts
  libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx
  libs/insight-viewer/src/components/EditPointer/index.tsx
  libs/insight-viewer/src/hooks/useAnnotation/index.ts
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
  package-lock.json
  package.json
  rfcs/0000_RFC_TEMPLATE.md
Labels: bug, enhancement, minor
