Repository lunit-io/insight-viewer, pull requests merged in 2022-05, with the labels that each got.

#245 Hotfix/5.5.2/viewport
  apps/insight-viewer-docs/src/containers/Annotation/Viewer/index.tsx
  apps/insight-viewer-docs/src/containers/Measurement/Viewer/index.tsx
  packages/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  packages/insight-viewer/src/Viewer/CircleViewer/index.tsx
  packages/insight-viewer/src/Viewer/LineViewer/index.tsx
  packages/insight-viewer/src/Viewer/PolygonViewer/index.tsx
  packages/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  packages/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  packages/insight-viewer/src/Viewer/RulerViewer/index.tsx
  packages/insight-viewer/src/hooks/useAnnotation/index.ts
  packages/insight-viewer/src/hooks/useAnnotationDrawing/index.ts
  packages/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  packages/insight-viewer/src/hooks/useDrawingHandler/index.ts
  packages/insight-viewer/src/hooks/useMeasurement/index.ts
  packages/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  packages/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
  packages/insight-viewer/src/utils/common/calculateDistance.ts
  packages/insight-viewer/src/utils/common/getCircleRadius.ts
  packages/insight-viewer/src/utils/common/getDrewAnnotation.ts
  packages/insight-viewer/src/utils/common/getDrewMeasurement.ts
  packages/insight-viewer/src/utils/common/getEditPointPosition.ts
  packages/insight-viewer/src/utils/common/getLineLengthWithoutImage.ts
  packages/insight-viewer/src/utils/common/getPolyProps.ts
Labels: bug

#247 Feature/text annotation
  apps/insight-viewer-docs/mocks/texts.ts
  apps/insight-viewer-docs/src/containers/Annotation/Drawer/index.tsx
  apps/insight-viewer-docs/src/containers/Annotation/Viewer/index.tsx
  packages/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  packages/insight-viewer/src/Viewer/AnnotationViewer/AnnotationViewer.styles.ts
  packages/insight-viewer/src/Viewer/AnnotationViewer/index.tsx
  packages/insight-viewer/src/Viewer/TextDrawer/TextDrawer.types.ts
  packages/insight-viewer/src/Viewer/TextDrawer/Typing.tsx
  packages/insight-viewer/src/Viewer/TextDrawer/Typing.types.ts
  packages/insight-viewer/src/Viewer/TextDrawer/index.tsx
  packages/insight-viewer/src/Viewer/TextViewer/TextViewer.types.ts
  packages/insight-viewer/src/Viewer/TextViewer/index.tsx
  packages/insight-viewer/src/const/index.ts
  packages/insight-viewer/src/index.ts
  packages/insight-viewer/src/types/index.ts
  packages/insight-viewer/src/utils/common/getAnnotationDrawingPoints.ts
  packages/insight-viewer/src/utils/common/getDrewAnnotation.ts
Labels: enhancement

#249 Feature/update deps
  packages/insight-viewer/package.json
  packages/insight-viewer/src/const/index.ts
  packages/insight-viewer/src/hooks/useInteraction/useHandleClick/index.ts
  packages/insight-viewer/src/hooks/useInteraction/useHandleDrag/index.ts
  packages/insight-viewer/src/hooks/useInteraction/useHandleWheel/index.ts
  packages/insight-viewer/src/hooks/useMultipleImages/loadImages.ts
  yarn.lock
Labels: dependencies
