Repository lunit-io/insight-viewer, pull requests merged in 2022-10, with the labels that each got.

#325 VIEWER-64 / modify edit pointer width
  libs/insight-viewer/src/Viewer/Viewer.styles.ts
Labels: enhancement

#327 Fix e2e test
  apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts
  apps/insight-viewer-docs-e2e/src/e2e/basic.cy.ts
  apps/insight-viewer-docs-e2e/src/e2e/multiframe.cy.ts
  apps/insight-viewer-docs/components/ImageSelect/useImageSelect.tsx
  apps/insight-viewer-docs/const.ts
  apps/insight-viewer-docs/containers/Annotation/Viewer/index.tsx
  apps/insight-viewer-docs/containers/Error/Base.tsx
  apps/insight-viewer-docs/containers/Error/Custom.tsx
  apps/insight-viewer-docs/containers/Interaction/Custom.tsx
  apps/insight-viewer-docs/containers/Interaction/Image1.tsx
  apps/insight-viewer-docs/containers/Measurement/Viewer/index.tsx
  apps/insight-viewer-docs/containers/MultiFrame/Base.tsx
  apps/insight-viewer-docs/containers/Overlay/index.tsx
  apps/insight-viewer-docs/containers/Progress/Base.tsx
  apps/insight-viewer-docs/containers/Progress/Custom.tsx
  apps/insight-viewer-docs/containers/UseOverlayContext/Contour/index.tsx
  apps/insight-viewer-docs/containers/UseOverlayContext/Heatmap/index.tsx
  apps/insight-viewer-docs/containers/Viewport/Image1.tsx
  apps/insight-viewer-docs/containers/Viewport/Image2.tsx
  apps/insight-viewer-docs/containers/ViewportReset/MultiFrame/Images.tsx
  apps/insight-viewer-docs/containers/ViewportReset/MultiFrame/useCaseSelect.tsx
  apps/insight-viewer-docs/mocks/handlers.ts
  libs/fixtures/src/annotation/circles.ts
  libs/fixtures/src/annotation/contours.ts
  libs/fixtures/src/annotation/freeLines.ts
  libs/fixtures/src/annotation/lines.ts
  libs/fixtures/src/annotation/polygons.ts
  libs/fixtures/src/annotation/rulers.ts
  libs/fixtures/src/annotation/texts.ts
  libs/fixtures/src/image/index.ts
  libs/fixtures/src/index.ts
  package.json
Labels: tests

#329 VIEWER-67 / Prevent dragging when hovered
  libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts
  libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.types.ts
  libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts
  libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
  libs/insight-viewer/src/hooks/useDrawingHandler/types.ts
  libs/insight-viewer/src/hooks/useMeasurement/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
Labels: bug

#328 VIEWER-43 / Annotation, Measurement list issue
  libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx
  libs/insight-viewer/src/Viewer/AnnotationViewer/AnnotationViewer.types.ts
  libs/insight-viewer/src/Viewer/AnnotationViewer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementViewer/MeasurementViewer.types.ts
  libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx
  libs/insight-viewer/src/hooks/useAnnotation/index.ts
  libs/insight-viewer/src/hooks/useMeasurement/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/utils/common/getMeasurement.ts
Labels: enhancement

#334 VIEWER-75 / Fix Edit not working bug
  libs/insight-viewer/src/Viewer/AnnotationViewer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementOverlay/MeasurementOverlay.types.ts
  libs/insight-viewer/src/Viewer/MeasurementOverlay/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementViewer/MeasurementViewer.types.ts
  libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx
  libs/insight-viewer/src/hooks/useAnnotation/index.ts
  libs/insight-viewer/src/hooks/useMeasurement/index.ts
Labels: bug

#339 VIEWER-76 / useViewport reset 동작 버그
  apps/insight-viewer-docs/containers/Interaction/Image1.tsx
  libs/insight-viewer/src/hooks/useViewport.ts
Labels: bug

#344 Feature modify class name for cursor
  apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx
  apps/insight-viewer-docs/containers/Annotation/Viewer/index.tsx
  apps/insight-viewer-docs/containers/Measurement/Drawer/index.tsx
  apps/insight-viewer-docs/containers/Measurement/Viewer/index.tsx
  apps/insight-viewer-docs/styles/globals.css
  libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  libs/insight-viewer/src/Viewer/CircleDrawer/CircleDrawer.types.ts
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
  libs/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts
  libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerDrawer/RulerDrawer.types.ts
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  libs/insight-viewer/src/Viewer/TextDrawer/TextDrawer.types.ts
  libs/insight-viewer/src/Viewer/TextDrawer/index.tsx
  libs/insight-viewer/src/Viewer/TextViewer/index.tsx
  libs/insight-viewer/src/Viewer/Viewer.styles.ts
  libs/insight-viewer/src/components/EditPointer/index.tsx
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
  libs/insight-viewer/src/types/index.ts
  libs/insight-viewer/src/utils/common/getCursorStatus.spec.ts
  libs/insight-viewer/src/utils/common/getCursorStatus.ts
  libs/insight-viewer/src/utils/common/setClassName.spec.ts
  libs/insight-viewer/src/utils/common/setClassName.ts
Labels: enhancement

#348 hotfix / delete circle drawer cursor style
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
Labels: bug, patch

#349 feat(viewer): remove delete key handling code
  libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
Labels: enhancement

#350 VIEWER-55 / apply changed circle editting
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.ts
  libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.ts
  libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.ts
Labels: enhancement, minor

#351 Release/6.1.0
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.ts
  libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.ts
  libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.ts
  package-lock.json
  package.json
Labels: bug, enhancement, minor

#352 Fix/initial annotation
  libs/insight-viewer/src/hooks/useAnnotation/index.ts
  libs/insight-viewer/src/hooks/useMeasurement/index.ts
Labels: bug, enhancement

#354 reset states of useAnnotationPointsHandler hook (measurement)
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
Labels: bug, minor

#355 Release/6.1.1
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/hooks/useAnnotation/index.ts
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useMeasurement/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  package-lock.json
  package.json
Labels: bug, patch

#356 VIEWER-84 / add tests of circle edit points
  libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
Labels: tests
