Repository lunit-io/insight-viewer, pull requests merged in 2022-08, with the labels that each got.

#273 VIEWER-27 / Add timeout option to useImage
  apps/insight-viewer-docs/src/containers/Basic/Code.ts
  packages/insight-viewer/src/const/index.ts
  packages/insight-viewer/src/hooks/useImage/index.ts
  packages/insight-viewer/src/hooks/useImage/loadCornerstoneImage.ts
  packages/insight-viewer/src/hooks/useImage/loadImage.ts
  packages/insight-viewer/src/hooks/useImage/types.ts
  packages/insight-viewer/src/hooks/useMultipleImages/index.ts
  packages/insight-viewer/src/hooks/useMultipleImages/loadCornerstoneImages.ts
  packages/insight-viewer/src/hooks/useMultipleImages/loadImages.ts
  packages/insight-viewer/src/hooks/useMultipleImages/useLoadImages.ts
  packages/insight-viewer/src/utils/httpClient/index.ts
Labels: bug, enhancement

#270 VIEWER-22 / VIEWER-23 / add arrow outline style, modify arrow scale
  packages/insight-viewer/src/Viewer/LineViewer/index.tsx
  packages/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  packages/insight-viewer/src/utils/common/getArrowPosition.ts
  packages/insight-viewer/src/utils/common/getPolyProps.ts
Labels: enhancement

#274 VIEWER-30 / Update Annotation Viewer docs mock data
  apps/insight-viewer-docs/mocks/freeLines.ts
  apps/insight-viewer-docs/mocks/lines.ts
  apps/insight-viewer-docs/mocks/polygons.ts
  apps/insight-viewer-docs/src/containers/Annotation/Viewer/index.tsx
  apps/insight-viewer-docs/src/containers/Measurement/Viewer/index.tsx
Labels: documentation

#275 VIEWER-29 / Delete headPoints field, add hasArrowHead field to Line Annotation
  apps/insight-viewer-docs/mocks/lines.ts
  packages/insight-viewer/src/types/index.ts
  packages/insight-viewer/src/utils/common/getDrewAnnotation.ts
  packages/insight-viewer/src/utils/common/getPolyProps.ts
Labels: enhancement

#276 feat(viewer): add line spacing and apply line annotation label position
  packages/insight-viewer/src/const/index.ts
  packages/insight-viewer/src/utils/common/getDrewAnnotation.ts
Labels: enhancement

#277 fix(viewer-docs): wrong hostname in loader worker setting
  apps/insight-viewer-docs/src/containers/Basic/Code.ts
  apps/insight-viewer-docs/src/containers/Basic/ImageSelectableViewer.tsx
Labels: documentation

#280 VIEWER-9 / Add unit test for util functions
  packages/insight-viewer/src/Viewer/LineViewer/index.tsx
  packages/insight-viewer/src/Viewer/PolygonViewer/index.tsx
  packages/insight-viewer/src/mocks/utils.ts
  packages/insight-viewer/src/utils/common/calcuateDisatance.spec.ts
  packages/insight-viewer/src/utils/common/calculateDistance.ts
  packages/insight-viewer/src/utils/common/getAnnotationDrawingPoints.spec.ts
  packages/insight-viewer/src/utils/common/getAnnotationEditingPoints.spec.ts
  packages/insight-viewer/src/utils/common/getArrowPosition.spec.ts
  packages/insight-viewer/src/utils/common/getCircleCenterAndEndPoint.spec.ts
  packages/insight-viewer/src/utils/common/getCircleConnectingLine.spec.ts
  packages/insight-viewer/src/utils/common/getCircleEditPoints.spec.ts
  packages/insight-viewer/src/utils/common/getCircleRadius.spec.ts
  packages/insight-viewer/src/utils/common/getCircleTextPosition.spec.ts
  packages/insight-viewer/src/utils/common/getDrawingMeasurement.spec.ts
  packages/insight-viewer/src/utils/common/getDrewAnnotation.spec.ts
  packages/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
  packages/insight-viewer/src/utils/common/getExistingMeasurementPoints.spec.ts
  packages/insight-viewer/src/utils/common/getIsPolygonAreaGreaterThanArea.spec.ts
  packages/insight-viewer/src/utils/common/getLineLength.spec.ts
  packages/insight-viewer/src/utils/common/getLineLengthWithoutImage.spec.ts
  packages/insight-viewer/src/utils/common/getMeasurement.spec.ts
  packages/insight-viewer/src/utils/common/getMeasurementDrawingPoints.spec.ts
  packages/insight-viewer/src/utils/common/getMeasurementEditingPoints.spec.ts
  packages/insight-viewer/src/utils/common/getMeasurementPoints.spec.ts
  packages/insight-viewer/src/utils/common/getMovedPoints.spec.ts
  packages/insight-viewer/src/utils/common/getPolyViewerInfo.spec.ts
  packages/insight-viewer/src/utils/common/getPolyViewerInfo.ts
  packages/insight-viewer/src/utils/common/getRulerConnectingLine.spec.ts
  packages/insight-viewer/src/utils/common/getRulerTextPosition.spec.ts
  packages/insight-viewer/src/utils/common/getTextPosition.spec.ts
Labels: tests

#283 VIEWER-31 / update circle measurement mock data
  apps/insight-viewer-docs/mocks/circles.ts
Labels: documentation

#286 VIEWER-7 / delete legacy test code, util function
  apps/insight-viewer-docs/cypress/integration/useOverlayContext.SvgContourDrawer.spec.ts
  apps/insight-viewer-docs/cypress/integration/useOverlayContext.SvgContourViewer.spec.ts
  packages/insight-viewer/src/utils/common/checkFocusedCircle.ts
  packages/insight-viewer/src/utils/common/getConnectingLine.ts
  packages/insight-viewer/src/utils/common/getDrawingTextPosition.ts
Labels: tests

#282 VIEWER-34 / Annotation Viewer Drawer E2E test code
  apps/insight-viewer-docs/cypress/integration/annotation.drawer.spec.ts
  apps/insight-viewer-docs/cypress/integration/annotation.viewer.spec.ts
  apps/insight-viewer-docs/cypress/integration/overlay.spec.ts
  apps/insight-viewer-docs/cypress/support/utils.ts
  apps/insight-viewer-docs/mocks/freeLines.ts
  apps/insight-viewer-docs/mocks/lines.ts
  apps/insight-viewer-docs/mocks/polygons.ts
  apps/insight-viewer-docs/src/containers/Annotation/Drawer/index.tsx
  apps/insight-viewer-docs/src/containers/Annotation/Viewer/index.tsx
  apps/insight-viewer-docs/src/containers/Interaction/Base.tsx
  apps/insight-viewer-docs/src/containers/Interaction/Image2.tsx
  packages/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  packages/insight-viewer/src/utils/common/isValidLength.ts
Labels: tests

#284 VIEWER-36 / Measurement Viewer Drawer E2E test code
  apps/insight-viewer-docs/cypress/integration/annotation.drawer.spec.ts
  apps/insight-viewer-docs/cypress/integration/measurement.drawer.spec.ts
  apps/insight-viewer-docs/cypress/integration/measurement.viewer.spec.ts
  apps/insight-viewer-docs/cypress/integration/multiframe.spec.ts
  apps/insight-viewer-docs/cypress/support/utils.ts
  apps/insight-viewer-docs/mocks/ruler.ts
  apps/insight-viewer-docs/src/containers/Measurement/Drawer/index.tsx
  apps/insight-viewer-docs/src/containers/Measurement/Viewer/index.tsx
  packages/insight-viewer/src/Viewer/CircleViewer/index.tsx
  packages/insight-viewer/src/Viewer/MeasurementViewer/index.tsx
  packages/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  packages/insight-viewer/src/Viewer/RulerViewer/index.tsx
Labels: tests

#292 VIEWER-40 / refactoring useAnnotationPointsHandler
  packages/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  packages/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts
  packages/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  packages/insight-viewer/src/Viewer/TextDrawer/TextDrawer.types.ts
  packages/insight-viewer/src/Viewer/TextDrawer/index.tsx
  packages/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  packages/insight-viewer/src/hooks/useAnnotationPointsHandler/types.ts
  packages/insight-viewer/src/mocks/circle.ts
  packages/insight-viewer/src/mocks/freeLines.ts
  packages/insight-viewer/src/mocks/lines.ts
  packages/insight-viewer/src/mocks/polygons.ts
  packages/insight-viewer/src/mocks/text.ts
  packages/insight-viewer/src/utils/common/checkIsInitialAnnotation.spec.ts
  packages/insight-viewer/src/utils/common/checkIsInitialAnnotation.ts
  packages/insight-viewer/src/utils/common/getAnnotationEditingPoints.spec.ts
  packages/insight-viewer/src/utils/common/getAnnotationEditingPoints.ts
  packages/insight-viewer/src/utils/common/getAnnotationPoints.spec.ts
  packages/insight-viewer/src/utils/common/getAnnotationPoints.ts
  packages/insight-viewer/src/utils/common/getDrawingAnnotation.spec.ts
  packages/insight-viewer/src/utils/common/getDrawingAnnotation.ts
  packages/insight-viewer/src/utils/common/getDrewAnnotation.spec.ts
  packages/insight-viewer/src/utils/common/getDrewAnnotation.ts
  packages/insight-viewer/src/utils/common/getExistingAnnotationPoints.spec.ts
  packages/insight-viewer/src/utils/common/getExistingAnnotationPoints.ts
  packages/insight-viewer/src/utils/common/getInitialAnnotation.spec.ts
  packages/insight-viewer/src/utils/common/getInitialAnnotation.ts
Labels: enhancement

#294 VIEWER-35 / Change Logo
  apps/insight-viewer-docs/components/Layout/index.tsx
  apps/insight-viewer-docs/components/Logo/index.tsx
  package-lock.json
  package.json
Labels: enhancement

#293 Viewer-41 / Measurement refactor ver.1
  apps/insight-viewer-docs-e2e/src/support/utils.ts
  apps/insight-viewer-docs/mocks/circles.ts
  apps/insight-viewer-docs/mocks/ruler.ts
  libs/insight-viewer/src/Viewer/CircleDrawer/CircleDrawer.types.ts
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/Viewer/CircleViewer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerDrawer/RulerDrawer.types.ts
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerViewer/index.tsx
  libs/insight-viewer/src/hooks/useMeasurement/index.ts
  libs/insight-viewer/src/hooks/useMeasurement/types.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/types.ts
  libs/insight-viewer/src/types/index.ts
  libs/insight-viewer/src/utils/common/getCircleRadius.ts
  libs/insight-viewer/src/utils/common/getConnectingLinePoints.spec.ts
  libs/insight-viewer/src/utils/common/getConnectingLinePoints.ts
  libs/insight-viewer/src/utils/common/getDrawingMeasurement.spec.ts
  libs/insight-viewer/src/utils/common/getDrawingMeasurement.ts
  libs/insight-viewer/src/utils/common/getExistingMeasurementPoints.spec.ts
  libs/insight-viewer/src/utils/common/getExistingMeasurementPoints.ts
  libs/insight-viewer/src/utils/common/getMeasurement.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurement.ts
  libs/insight-viewer/src/utils/common/getMeasurementPoints.spec.ts
  libs/insight-viewer/src/utils/common/getTextPosition.spec.ts
  libs/insight-viewer/src/utils/common/index.spec.ts
Labels: enhancement, major
