Repository lunit-io/insight-viewer, pull requests merged in 2022-09, with the labels that each got.

#295 VIEWER-26 / Fix Drawer Error
  libs/insight-viewer/src/hooks/useAnnotationPointsHandler/index.ts
  libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
Labels: bug

#296 Viewer-41 / Measurement refactor ver.2
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/Viewer/CircleViewer/index.tsx
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/utils/common/getCircleConnectingLine.ts
  libs/insight-viewer/src/utils/common/getCircleEndPoint.spec.ts
  libs/insight-viewer/src/utils/common/getCircleEndPoint.ts
  libs/insight-viewer/src/utils/common/getCircleRadius.spec.ts
  libs/insight-viewer/src/utils/common/getCircleRadius.ts
  libs/insight-viewer/src/utils/common/getDrewAnnotation.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.ts
  libs/insight-viewer/src/utils/common/getExistingMeasurementPoints.spec.ts
  libs/insight-viewer/src/utils/common/getExistingMeasurementPoints.ts
  libs/insight-viewer/src/utils/common/getInitialAnnotation.ts
  libs/insight-viewer/src/utils/common/getLineLengthWithoutImage.spec.ts
  libs/insight-viewer/src/utils/common/getLineLengthWithoutImage.ts
  libs/insight-viewer/src/utils/common/getMeasurement.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurement.ts
  libs/insight-viewer/src/utils/common/getMeasurementPoints.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurementPoints.ts
Labels: enhancement

#297 VIEWER-24 / Annotation, Measurement Extend Select Area
  libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.styles.ts
  libs/insight-viewer/src/Viewer/AnnotationViewer/AnnotationViewer.styles.ts
  libs/insight-viewer/src/Viewer/CircleDrawer/CircleDrawer.styles.ts
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/Viewer/CircleViewer/CircleViewer.styles.ts
  libs/insight-viewer/src/Viewer/CircleViewer/index.tsx
  libs/insight-viewer/src/Viewer/LineViewer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.styles.ts
  libs/insight-viewer/src/Viewer/MeasurementViewer/MeasurementViewer.styles.ts
  libs/insight-viewer/src/Viewer/PolygonViewer/index.tsx
  libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerDrawer/RulerDrawer.styles.ts
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerViewer/index.tsx
  libs/insight-viewer/src/components/EditPointer/index.tsx
  libs/insight-viewer/src/types/index.ts
Labels: enhancement

#298 VIEWER-18 / Refactoring Annotation, Measurement style constant
  libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.styles.ts
  libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  libs/insight-viewer/src/Viewer/AnnotationViewer/AnnotationViewer.styles.ts
  libs/insight-viewer/src/Viewer/AnnotationViewer/index.tsx
  libs/insight-viewer/src/Viewer/CircleDrawer/CircleDrawer.styles.ts
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/Viewer/CircleViewer/CircleViewer.styles.ts
  libs/insight-viewer/src/Viewer/CircleViewer/index.tsx
  libs/insight-viewer/src/Viewer/LineViewer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementDrawer/MeasurementDrawer.styles.ts
  libs/insight-viewer/src/Viewer/MeasurementDrawer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementViewer/MeasurementViewer.styles.ts
  libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx
  libs/insight-viewer/src/Viewer/PolygonViewer/index.tsx
  libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerDrawer/RulerDrawer.styles.ts
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerViewer/index.tsx
  libs/insight-viewer/src/Viewer/TextDrawer/Typing.tsx
  libs/insight-viewer/src/Viewer/TextDrawer/index.tsx
  libs/insight-viewer/src/Viewer/TextViewer/index.tsx
  libs/insight-viewer/src/Viewer/Viewer.styles.ts
  libs/insight-viewer/src/components/EditPointer/index.tsx
Labels: enhancement

#305 Viewer-47 / modify text position
  apps/insight-viewer-docs/containers/HttpHeader/WithJwt.tsx
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerViewer/index.tsx
  libs/insight-viewer/src/const/index.ts
  libs/insight-viewer/src/utils/common/calculateLengthBetweenPoints.spec.ts
  libs/insight-viewer/src/utils/common/calculateLengthBetweenPoints.ts
  libs/insight-viewer/src/utils/common/getLineLength.ts
  libs/insight-viewer/src/utils/common/getRulerTextPosition.spec.ts
  libs/insight-viewer/src/utils/common/getRulerTextPosition.ts
Labels: bug

#307 Hotfix / publish code change
  libs/insight-viewer/project.json
  tools/scripts/publish.mjs
Labels: patch

#308 Hotfix / delete unused tag option of publish command
  tools/scripts/publish.mjs
Labels: patch

#309 INSIGHT Viewer v5.8.1 release
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/project.json
  libs/insight-viewer/src/Viewer/Viewer.styles.ts
  package.json
  tools/scripts/publish.mjs
Labels: patch

#311 INSIGHT Viewer v5.8.2 release
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/Viewer/AnnotationViewer/index.tsx
  libs/insight-viewer/src/Viewer/MeasurementViewer/index.tsx
  libs/insight-viewer/src/Viewer/Viewer.styles.ts
  package.json
Labels: bug, patch

#314 INSIGHT Viewer v5.8.3 release
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/Viewer/AnnotationDrawer/AnnotationDrawer.types.ts
  libs/insight-viewer/src/Viewer/AnnotationDrawer/index.tsx
  libs/insight-viewer/src/Viewer/AnnotationOverlay/index.tsx
  libs/insight-viewer/src/Viewer/PolylineDrawer/PolylineDrawer.types.ts
  libs/insight-viewer/src/Viewer/PolylineDrawer/index.tsx
  package.json
Labels: bug, documentation, patch

#306 VIEWER-2/ Change Circle Measurement Drawing
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/Viewer/CircleViewer/index.tsx
  libs/insight-viewer/src/hooks/useMeasurementPointsHandler/index.ts
  libs/insight-viewer/src/utils/common/getCircleCenterPoint.spec.ts
  libs/insight-viewer/src/utils/common/getCircleCenterPoint.ts
  libs/insight-viewer/src/utils/common/getCircleConnectingLine.ts
  libs/insight-viewer/src/utils/common/getCircleRadius.spec.ts
  libs/insight-viewer/src/utils/common/getCircleRadius.ts
  libs/insight-viewer/src/utils/common/getCircleStartPoint.spec.ts
  libs/insight-viewer/src/utils/common/getCircleStartPoint.ts
  libs/insight-viewer/src/utils/common/getDrewAnnotation.spec.ts
  libs/insight-viewer/src/utils/common/getDrewAnnotation.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.spec.ts
  libs/insight-viewer/src/utils/common/getEditPointPosition.ts
  libs/insight-viewer/src/utils/common/getMeasurement.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurement.ts
  libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurementEditingPoints.ts
  libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.spec.ts
  libs/insight-viewer/src/utils/common/getMeasurementPointsByMode.ts
  libs/insight-viewer/src/utils/common/getMovedPoints.ts
Labels: enhancement

#315 Viewer-52 / Parameterize useImage's HTTP client
  apps/insight-viewer-docs/containers/Basic/Code.ts
  apps/insight-viewer-docs/containers/Basic/DicomImageViewer.tsx
  libs/insight-viewer/src/hooks/useImage/getImageIdAndScheme.spec.ts
  libs/insight-viewer/src/hooks/useImage/getImageIdAndScheme.ts
  libs/insight-viewer/src/hooks/useImage/index.ts
  libs/insight-viewer/src/hooks/useImage/loadCornerstoneImage.ts
  libs/insight-viewer/src/hooks/useImage/loadImage.spec.ts
  libs/insight-viewer/src/hooks/useImage/loadImage.ts
  libs/insight-viewer/src/hooks/useImage/types.ts
  libs/insight-viewer/src/hooks/useMultipleImages/loadCornerstoneImages.ts
  libs/insight-viewer/src/types/index.ts
  libs/insight-viewer/src/utils/cornerstoneHelper/utils.ts
Labels: enhancement

#317 VIEWER-56 / Modify validation logic of added Annotation, Measurement
  libs/insight-viewer/src/const/index.ts
  libs/insight-viewer/src/hooks/useAnnotation/index.ts
  libs/insight-viewer/src/hooks/useMeasurement/index.ts
  libs/insight-viewer/src/utils/common/getAnnotationPoints.ts
  libs/insight-viewer/src/utils/common/getIsPolygonAreaGreaterThanArea.spec.ts
  libs/insight-viewer/src/utils/common/getIsPolygonAreaGreaterThanArea.ts
  libs/insight-viewer/src/utils/common/isLessThanTheMinimumPointsLength.spec.ts
  libs/insight-viewer/src/utils/common/isLessThanTheMinimumPointsLength.ts
  libs/insight-viewer/src/utils/common/isSamePoints.spec.ts
  libs/insight-viewer/src/utils/common/isSamePoints.ts
  libs/insight-viewer/src/utils/common/isValidLength.ts
Labels: bug, enhancement

#320 Viewer-52 / Fix parameterize useImage's HTTP client
  libs/insight-viewer/src/hooks/useImage/index.ts
Labels: bug

#321 INSIGHT Viewer v5.9.1 release
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/hooks/useImage/index.ts
  package.json
Labels: bug, patch

#316 VIEWER-49 / Remove IIFE
  libs/insight-viewer/src/hooks/useImage/index.ts
  libs/insight-viewer/src/hooks/useImageLoader/index.ts
Labels: enhancement

#322 VIEWER-63 / modify text point logic for editing text move mode
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
Labels: bug, patch

#323 INSIGHT Viewer v5.9.2 release
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  package.json
Labels: bug, patch

#324 VIEWER-64 / Modify connecting line
  libs/insight-viewer/src/Viewer/CircleDrawer/index.tsx
  libs/insight-viewer/src/Viewer/CircleViewer/index.tsx
  libs/insight-viewer/src/Viewer/RulerDrawer/index.tsx
  libs/insight-viewer/src/Viewer/RulerViewer/index.tsx
  libs/insight-viewer/src/hooks/useCircleMeasurement/index.ts
  libs/insight-viewer/src/hooks/useRulerMeasurement/index.ts
  libs/insight-viewer/src/hooks/useTextBox/index.ts
  libs/insight-viewer/src/utils/common/modifyConnectingLine.spec.ts
  libs/insight-viewer/src/utils/common/modifyConnectingLine.ts
  libs/insight-viewer/src/utils/common/stringifyPoints.spec.ts
  libs/insight-viewer/src/utils/common/stringifyPoints.ts
Labels: enhancement

#326 VIEWER-64 / Modify finding connectingLine logic
  libs/insight-viewer/src/hooks/useRulerMeasurement/index.ts
  libs/insight-viewer/src/utils/common/getConnectingLinePoints.ts
  libs/insight-viewer/src/utils/common/getRulerConnectingLine.spec.ts
  libs/insight-viewer/src/utils/common/getRulerConnectingLine.ts
Labels: bug
