Repository lunit-io/insight-viewer, pull requests merged in 2022-12, with the labels that each got.

#373 VIEWER-121 / add mouse left click validation when annotation drawing
  libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
Labels: bug, patch

#374 Release/6.2.1
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
  package-lock.json
  package.json
Labels: bug, patch

#376 Release/6.1.3
  CHANGELOG.md
  apps/insight-viewer-docs-e2e/CHANGELOG.md
  apps/insight-viewer-docs/CHANGELOG.md
  libs/fixtures/CHANGELOG.md
  libs/fixtures/package.json
  libs/insight-viewer/CHANGELOG.md
  libs/insight-viewer/package.json
  libs/insight-viewer/src/hooks/useDrawingHandler/index.ts
  package-lock.json
  package.json
Labels: bug, patch

#372 VIEWER-8 / fix Annotation, Measurement test code
  apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts
  apps/insight-viewer-docs-e2e/src/e2e/annotation.viewer.cy.ts
  apps/insight-viewer-docs-e2e/src/e2e/measurement.viewer.cy.ts
  apps/insight-viewer-docs-e2e/src/support/utils.ts
  apps/insight-viewer-docs/containers/Annotation/Drawer/index.tsx
  apps/insight-viewer-docs/containers/Annotation/Viewer/index.tsx
  apps/insight-viewer-docs/containers/Measurement/Viewer/index.tsx
Labels: tests

#378 VIEWER-124 / fix useViewport reset bug
  apps/insight-viewer-docs/containers/Interaction/Tabs.tsx
  libs/insight-viewer/src/hooks/useViewport.ts
  libs/insight-viewer/src/hooks/useViewportUpdate.ts
Labels: bug

#379 VIEWER-88 / add default mouse wheel interaction function
  apps/insight-viewer-docs/containers/Interaction/Image2.tsx
  libs/insight-viewer/src/hooks/useInteraction/types.ts
  libs/insight-viewer/src/hooks/useInteraction/useHandleWheel/control.ts
  libs/insight-viewer/src/hooks/useInteraction/useHandleWheel/index.ts
  libs/insight-viewer/src/hooks/useInteraction/useViewportInteraction.ts
Labels: enhancement

#380 VIEWER-96 / add arrow line annotation test
  apps/insight-viewer-docs-e2e/src/e2e/annotation.drawer.cy.ts
Labels: tests
